version: "3.8"
services:
  api:
    container_name: tapwallet_api_${NODE_ENV}
    image: tapwallet_api_${NODE_ENV}
    environment:
    - NODE_ENV=${NODE_ENV}
    build:
      context: .
      target: ${NODE_ENV}
      dockerfile: Dockerfile
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules
    ports:
    - ${PORT}:${PORT}
    - 9229:9229
    command: npm run start:${NODE_ENV}
    env_file: 
    - .env
    networks: 
    - tapwallet
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
    - ${POSTGRES_DB_PORT}:${POSTGRES_DB_PORT}
    volumes:
    - ./pgdata:/postgresdata
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/postgresdata
    networks:
      - tapwallet
  pgadmin:
    links:
    - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - "8080:80"
    volumes:
    - ./pgdata/pgadmin:/root/ .pgadmin
    env_file:
    - .env
    networks: 
    - tapwallet
  redis:
    image: "redis:alpine"
    ports: 
    - "6379:6379"
    networks:
      - tapwallet
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"
    depends_on:
      - redis
    networks:
      - tapwallet
networks: 
 tapwallet: