name: Deploy-staging

on: 
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu:latest
    steps:
    - name: checkout
    - uses: actions/checkout@v2
    - name: deploy
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: tapmoney-staging
        heroku_email: degokeadewoye@gmail.com
        useDocker: true